development:
  adapter: sqlite3
  encoding: unicode
  database: kingraveninsults_development
  pool: 5
  username: kingraveninsults_developement
  password:
	  
test:
  adapter: postgresql
  encoding: unicode
  database: kingraveninsults_test
  pool: 5
  username: kingraveninsults_test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kingraveninsults_production
  pool: 5
  username: kingraveninsults
  password:
