development:
  adapter: sqlite3
  encoding: unicode
  database: kingraveninsults_development
  pool: 5
  username: tristanpendergrass
  password:
	  
test:
  adapter: sqlite3
  encoding: unicode
  database: kingraveninsults_test
  pool: 5
  username: kingraveninsults
  password:

production:
  adapter: sqlite3
  encoding: unicode
  database: kingraveninsults_production
  pool: 5
  username: kingraveninsults
  password:
